### PR TITLE
Update to angular 7

### PR DESCRIPTION
**Pull request by samtsai**
This seems to work fine:
https://stackblitz.com/edit/ngx-file-helpers-demo-emcdtq?file=package.json

### CODE REVIEW

**Comment by fvilers** [comment]
Thanks for your PR. I'd like to handle this by myself as I planned to use the new Angular CLI project that supports building a library.

I'll make a release this week to upgrade to Angular 7 but your work has been appreciated.

**Comment by samtsai** [comment]
Of course!  I was also going to suggest just generating the library anew with CLI :), if you need assistance with that, I can also help here, but thanks for your project!

**Comment by fvilers** [comment]
I'm almost done, but thanks. I'll keep you posted so that you can, if you wish to, test it when it will be released.

**Comment by fvilers** [comment]
If you'd like to, you can have a look at https://github.com/fvilers/ngx-file-helpers/tree/angular7

**Comment by samtsai** [comment]
I tested it locally and it looks good to me

**Comment by fvilers** [comment]
@samtsai Thanks a lot for your feedback!

**Pull request closed without merging**
