### PR TITLE
Update to Angular 17

### PR DESCRIPTION
**Pull request by NetWin**
## Changes
- Update Angular to version 17 (via `ng update`)
- Update other dependencies to their latest version
- Replace legacy material components

### CODE REVIEW

**Comment by NetWin** [comment]
@fvilers Not sure why i can't request a review. But can you have a look? 🙏🏼

**Comment by fvilers** [comment]
Thanks for the PR, will merge immediately and release a new major version.

**Comment by NetWin** [comment]
Thank you very much!

**Comment by fvilers** [comment]
Thanks to you @NetWin, you did the job!

**Pull request merged**
