### PR TITLE
Update to Angular 14

### PR DESCRIPTION
**Pull request by NetWin**
### Changes
- Executed `ng update @angular/cli` and `ng update @angular/material`
- Updated other non Angular dependencies to their latest version
- Updated projects peer dependencies

### CODE REVIEW

**Comment by sandersdevelopments** [comment]
nice! can it be merged asap?

**Comment by fvilers** [comment]
Thanks for the PR !

**Comment by fvilers** [comment]
Version 8.0.0 with Angular 14 support has been published to npm.

**Comment by NetWin** [comment]
Thank you very much 🚀

**Comment by fvilers** [comment]
Thanks to you @NetWin ;-)

**Pull request merged**
